### ISSUE TITLE
Are these cloudtrails intentionally not multi-region?

### ISSUE THREAD

**Issue by lvh** [cloudposse/terraform-aws-cloudtrail#18]
Is the intention that someone creates their own multi-region trail including global service events?

**Comment by goruha** [comment]
@osterman @aknysh can you check this?

**Comment by aknysh** [comment]
@lvh 
we have a variable to specify if a trail is multi-region or not
https://github.com/cloudposse/terraform-aws-cloudtrail/blob/master/variables.tf#L39

is that what you are asking?

**Comment by lvh** [comment]
Right, but they're false by default: I'm wondering if _that_ is intentional. Is the idea that people create their own global/multi-region trails?

(For security purpose, I like having global and multi-region trails, obviously: otherwise, when I compromise some credentials, I just go hide in a different region--and lots of critical services are (or at least pretend to be) regionless. But maybe I misunderstand the point of having per-region CloudTrails that don't have that :-)

**Comment by osterman** [comment]
@lvh I think a default of `true` would be advisable as you might be implying. We don't have a strong argument against it. From a security perspective, makes sense to always have it set to `true`

**Comment by lvh** [comment]
Yeah, sorry I'm hedging this so much. We 100% tell customers who don't have (hardened) CloudTrail to a) have one trail b) multi-region, regionless c) validation enabled d) KMS and private S3 bucket and e) for bonus points: in a totally separate account that you don't look at until you need it (and you hope you don't).

I'm just wondering if there's an ops reason to do anything else, except point e) (I could see how CT logs are valuable to Ops debugging of course!)

**Comment by osterman** [comment]
@lvh agree totally. We actually set it to true when we deploy it. Just for some reason, we didn't default it.

Here's our reference implementation: 
https://github.com/cloudposse/terraform-root-modules/blob/master/aws/audit-cloudtrail/main.tf

And here's our reference architecture: (E.g. totally separate account)
https://github.com/cloudposse/audit.cloudposse.co

Our strategy is to use lots of different accounts. Each account corresponds to a github repo.

**Comment by Gowiem** [comment]
@lvh the default for this var is now `true` -- Closing out 👍
