### ISSUE TITLE
Getting deprecation warnings on plan

### ISSUE THREAD

**Issue by dzandt-mission** [cloudposse/terraform-aws-cloudtrail#58]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
Getting this output from terraform plan with the latest version (21.0)

│ Warning: Argument is deprecated
│
│   with module.cloudtrail_s3_bucket.module.s3_bucket.aws_s3_bucket.default[0],
│   on .terraform/modules/cloudtrail_s3_bucket.s3_bucket/main.tf line 1, in resource "aws_s3_bucket" "default":
│    1: resource "aws_s3_bucket" "default" {
│
│ Use the aws_s3_bucket_versioning resource instead

## Expected Behavior
No command deprecation warnings

## Steps to Reproduce
Configure the module as directed
Perform a terraform plan

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: OSX
 - Version: 21.0

**Comment by Nuru** [comment]
This issue is with `cloudtrail_s3_bucket` not `cloudtrail`, and has been fixed somewhere along the way anyway.
